### ISSUE TITLE
Error: JVM Error creating core [galaxy1]: org/apache/lucene/analysis/StopwordAnalyzerBase

### ISSUE THREAD

**Issue by kienvht** [tuan-nng/solr-vn-tokenizer#1]
Hi anh Tuấn. Rất cảm ơn anh về solr analyze dành cho tiếng việt.
Em cũng đang tìm hiểu về phần này. làm theo hướng dẫn của anh ok. Nó build ra đc file solr1.0.jar ( 8.8KB (8.772bytes))
Em copy vào /server/lib xong restart solr thì bị lỗi như sau
`org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: JVM Error creating core [galaxy1]: org/apache/lucene/analysis/StopwordAnalyzerBase`
Mong anh có thể kiểm tra lại giúp em với ạ. Cảm ơn anh

**Comment by tuan-nng** [comment]
Có thể bạn đang dùng phiên bản Solr cũ hơn so với phiên bản mình đã test (Solr 7.7.1)

Ngoài ra, mình cũng cần copy thêm một vài dependency jar nữa.
Mình đã update README cho rõ hơn

**Comment by kienvht** [comment]
Cảm ơn anh @tuan-nng , em cũng đang dùng Solr 7.7.1
Em làm theo README mới của anh thì okay rồi ạ ( copy thêm cả commons-cli-1.2.jar ) nữa là chạy ok rồi ạ. 
Chúc anh ngày mạnh khỏe ^^
